/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pr_PlateRecognition */

#ifndef _Included_pr_PlateRecognition
#define _Included_pr_PlateRecognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pr_PlateRecognition
 * Method:    plateRecognize
 * Signature: (J[B)[Lpr/PlateInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_pr_PlateRecognition_plateRecognize
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     pr_PlateRecognition
 * Method:    initPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_pr_PlateRecognition_initPath__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     pr_PlateRecognition
 * Method:    initPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_pr_PlateRecognition_initPath__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     pr_PlateRecognition
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pr_PlateRecognition_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
