/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pr_PlateInfo */

#ifndef _Included_pr_PlateInfo
#define _Included_pr_PlateInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pr_PlateInfo
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pr_PlateInfo_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
